DROP TABLE IF EXISTS user;

CREATE TABLE user (
	id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	screen_name VARCHAR(255) UNIQUE NOT NULL,
	name VARCHAR(255) NOT NULL,
	age INT NOT NULL,
	intro VARCHAR(255) NOT NULL,
	created_at DATETIME,
	updated_at DATETIME
);
